// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xbjluksuwobjrqwomtzl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhiamx1a3N1d29ianJxd29tdHpsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzcyMzcxNDAsImV4cCI6MjA1MjgxMzE0MH0.hmoo_q0Mw7DxJVGE4h_lSI2hSOlsvVaa1YVRro-mo_E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);